#!/usr/bin/env python
# Copyright (c) 2016 by Mathieu Servillat
# Licensed under MIT (https://github.com/mservillat/uws-server/blob/master/LICENSE)
"""
Replace the predictable tokens of the client users by random tokens

Previous versions generated the token of a new client user with
uuid5(APP_PATH + email), which can be computed by anyone who knows the install path and
the email. The token authenticates the user on the UWS server, and identifies the owner
of their jobs. This command gives a new random token to those users, in the client
database and in the server database (users and jobs), which must be on the same host
(same settings, e.g. in the Docker container).

    python -m uws_client.rotate_tokens            # dry run: list the users to update
    python -m uws_client.rotate_tokens --apply    # update the databases

Backup both databases before --apply. Users who use their token outside of the web
client (scripts...) will have to get the new one from their profile page.
"""

import argparse
import uuid

from uws_server import storage
from uws_server.settings import settings as server_settings

from .settings import APP_PATH, settings
from .uws_client import User, app, user_datastore


def legacy_token(email, app_path):
    """Token generated by previous versions"""
    return str(uuid.uuid5(uuid.NAMESPACE_X500, app_path + email))


def rotate(apply=False, rotate_all=False, legacy_paths=(APP_PATH,)):
    job_storage = getattr(storage, server_settings.STORAGE + "JobStorage")()
    server = job_storage.Session()
    with app.app_context():
        users = User.query.order_by(User.email).all()
        to_rotate = []
        for user in users:
            if user.email == settings.ADMIN_NAME:
                continue  # token set from ADMIN_TOKEN
            predictable = any(user.token == legacy_token(user.email, p) for p in legacy_paths)
            if predictable or rotate_all:
                to_rotate.append(user)
        print(f"{len(users)} client users, {len(to_rotate)} to update"
              f" ({'all' if rotate_all else 'predictable tokens'}):")
        for user in to_rotate:
            old = user.token
            new = settings.new_token()
            server_users = server.query(job_storage.User).filter_by(name=user.email, token=old)
            server_jobs = server.query(job_storage.Job).filter_by(owner=user.email, owner_token=old)
            print(f"  {user.email}: server user {server_users.count()}, server jobs {server_jobs.count()}")
            if apply:
                server_users.update({"token": new}, synchronize_session=False)
                server_jobs.update({"owner_token": new}, synchronize_session=False)
                server.commit()
                user.token = new
                user_datastore.put(user)
                user_datastore.commit()
    server.close()
    print("Databases updated" if apply else "Dry run, nothing changed (use --apply to update)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="update the databases")
    parser.add_argument("--all", action="store_true", help="update all users (except admin), not only predictable tokens")
    parser.add_argument(
        "--legacy-path", action="append", default=[],
        help="other install path used by previous versions (APP_PATH is always checked)",
    )
    args = parser.parse_args()
    rotate(apply=args.apply, rotate_all=args.all, legacy_paths=[APP_PATH, *args.legacy_path])
