#!/usr/bin/env python
# Copyright (c) 2016 by Mathieu Servillat
# Licensed under MIT (https://github.com/mservillat/uws-server/blob/master/LICENSE)
"""
Settings shared by the UWS server and client

Values are read, by order of priority, from:
    1. environment variables prefixed with OPUS_ (e.g. OPUS_BASE_URL)
    2. the .env file in the OPUS directory (same names, see .env.dist)
    3. settings_local.py (deprecated, move its content to .env)
    4. the defaults defined in the settings classes
Dicts and lists are given as JSON in environment variables and .env.
"""

import importlib.util
import os
import warnings

from pydantic import SecretStr, field_validator
from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
)

# Where is located the code of the web app
APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
ENV_FILE = os.path.join(APP_PATH, ".env")
SETTINGS_LOCAL_FILE = os.path.join(APP_PATH, "settings_local.py")


class SettingsLocalSource(PydanticBaseSettingsSource):
    """Values defined in settings_local.py (deprecated, to be moved to .env)"""

    def __init__(self, settings_cls):
        super().__init__(settings_cls)
        self.values = {}
        if os.path.isfile(SETTINGS_LOCAL_FILE):
            spec = importlib.util.spec_from_file_location(
                "settings_local", SETTINGS_LOCAL_FILE
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            self.values = {
                k: v
                for k, v in vars(module).items()
                if k in settings_cls.model_fields
            }
            if self.values:
                warnings.warn(
                    f"{SETTINGS_LOCAL_FILE} is deprecated, move its values to {ENV_FILE}",
                    DeprecationWarning,
                    stacklevel=2,
                )

    def get_field_value(self, field, field_name):
        return self.values.get(field_name), field_name, False

    def __call__(self):
        return dict(self.values)


class CommonSettings(BaseSettings):
    """Settings used by both the UWS server and client"""

    model_config = SettingsConfigDict(
        env_prefix="OPUS_",
        env_file=ENV_FILE,
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Where is located the data used/generated by the web app - has to be writable
    # for the web server (www, _www, apache...), relative to APP_PATH if not absolute
    VAR_PATH: str = "local_var"  # store var locally for quick test, prefer e.g. '/var/opt/opus'

    # URL of the web server
    BASE_URL: str = "http://localhost:8082"  # For local debug server with run_server.py
    UWS_CLIENT_ENDPOINT: str = "http://localhost:8080"  # For local debug server with run_client.py
    UWS_SERVER_ENDPOINT: str = "/uws"
    SCIM_ENDPOINT: str = "/scim"

    # Mail server
    MAIL_SERVER: str = "smtp."
    MAIL_PORT: int = 25
    SENDER_EMAIL: str = "no_reply@opus"

    # Admin name+token has access to user database changes (i.e. set permissions)
    ADMIN_NAME: str = "opus-admin"
    ADMIN_EMAIL: str = "admin@opus"
    # IMPORTANT: use a random string and keep it secret (same value for server and client)
    ADMIN_TOKEN: SecretStr = SecretStr("TBD")

    # Suffix to the log files (set for tests)
    LOG_FILE_SUFFIX: str = ""

    @field_validator("VAR_PATH")
    @classmethod
    def var_path_absolute(cls, v):
        return v if os.path.isabs(v) else os.path.join(APP_PATH, v)

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            SettingsLocalSource(settings_cls),
            file_secret_settings,
        )

    def export(self):
        """Dict of all settings and derived values, with secrets revealed

        Used to expose settings as module-level names (see uws_server/settings.py)
        """
        values = {}
        for name in list(type(self).model_fields) + list(type(self).model_computed_fields):
            value = getattr(self, name)
            if isinstance(value, SecretStr):
                value = value.get_secret_value()
            values[name] = value
        return values
