#!/usr/bin/env python
# Copyright (c) 2016 by Mathieu Servillat
# Licensed under MIT (https://github.com/mservillat/uws-server/blob/master/LICENSE)
"""
Settings shared by the UWS server and client

Values are read, by order of priority, from:
    1. environment variables prefixed with OPUS_ (e.g. OPUS_BASE_URL)
    2. the .env file in the OPUS directory (same names, see .env.dist)
    3. the defaults defined in the settings classes
Dicts and lists are given as JSON in environment variables and .env.
"""

import os
import warnings
from collections.abc import Callable

from pydantic import ImportString, SecretStr, field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from . import generators

# Where is located the code of the web app
APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
ENV_FILE = os.path.join(APP_PATH, ".env")


class CommonSettings(BaseSettings):
    """Settings used by both the UWS server and client"""

    model_config = SettingsConfigDict(
        env_prefix="OPUS_",
        env_file=ENV_FILE,
        env_file_encoding="utf-8",
        extra="ignore",
        hide_input_in_errors=True,  # do not show values (secrets) in validation errors
    )

    # Where is located the data used/generated by the web app - has to be writable
    # for the web server (www, _www, apache...), relative to APP_PATH if not absolute
    VAR_PATH: str = "local_var"  # store var locally for quick test, prefer e.g. '/var/opt/opus'

    # URL of the web server
    BASE_URL: str = "http://localhost:8082"  # For the development server (just server)
    UWS_CLIENT_ENDPOINT: str = "http://localhost:8080"  # For the development server (just client)
    UWS_SERVER_ENDPOINT: str = "/uws"
    SCIM_ENDPOINT: str = "/scim"

    # Mail server
    MAIL_SERVER: str = "smtp."
    MAIL_PORT: int = 25
    SENDER_EMAIL: str = "no_reply@opus"

    # Admin name+token has access to user database changes (i.e. set permissions)
    ADMIN_NAME: str = "opus-admin"
    ADMIN_EMAIL: str = "admin@opus"
    # IMPORTANT: use a random string and keep it secret (same value for server and client)
    ADMIN_TOKEN: SecretStr = SecretStr("TBD")

    # OpenID Connect Identity Providers (e.g. INDIGO-IAM), used by the client to sign in users, and
    # by the server to accept their access tokens (Bearer), list of:
    # {"title": "OIDC login",  # Label for the login button
    #  "description": "",  # Text shown when mouse placed on the login button
    #  "url_logo": "/static/images/openid.jpg",  # Icon for the login button
    #  "url": "https://<openid-server>/.well-known/openid-configuration",
    #  "client_id": "", "client_secret": "",  # generated by the Identity Provider (client only)
    #  "scope": "openid email profile",
    #  "audience": "",  # optional: audience requested by the client, and required by the server
    #  "logout_url": ""}  # optional: URL ending the session on the Identity Provider at logout, if it
    #                     # has no end_session_endpoint (e.g. https://<iam>/logout), not used by default
    OIDC_IDPS: list[dict] = []

    # Generator of the tokens of new users, as an import string "module:function"
    # (see opus_config/generators.py for the default and signature)
    TOKEN_GEN: ImportString[Callable[..., str]] = generators.token

    # Suffix to the log files (set for tests)
    LOG_FILE_SUFFIX: str = ""

    @field_validator("VAR_PATH")
    @classmethod
    def var_path_absolute(cls, v):
        return v if os.path.isabs(v) else os.path.join(APP_PATH, v)

    @model_validator(mode="after")
    def check_settings_local(self):
        # settings_local.py was used by previous versions, it is no longer read
        path = os.path.join(APP_PATH, "settings_local.py")
        if os.path.isfile(path):
            msg = (
                f"{path} is no longer read, convert it to {ENV_FILE} with:\n"
                f"    python generate_env.py --from settings_local.py > .env\n"
                f"then remove settings_local.py"
            )
            if not os.path.isfile(ENV_FILE):
                # do not start with the default settings instead of the local ones
                raise RuntimeError(msg)
            warnings.warn(msg, stacklevel=2)
        return self

    @model_validator(mode="after")
    def warn_default_secrets(self):
        for name in type(self).model_fields:
            value = getattr(self, name)
            if isinstance(value, SecretStr) and value.get_secret_value() in ("", "TBD", "TBD!"):
                warnings.warn(
                    f"OPUS_{name} is not set, define a random value in {ENV_FILE}",
                    stacklevel=2,
                )
        return self

    def new_token(self, context=None):
        # context is given by SQLAlchemy when used as a column default
        return self.TOKEN_GEN(context)

    def export(self):
        """Dict of all settings and derived values, with secrets revealed

        Used to expose settings as module-level names (see uws_server/settings.py)
        """
        values = {}
        for name in list(type(self).model_fields) + list(type(self).model_computed_fields):
            value = getattr(self, name)
            if isinstance(value, SecretStr):
                value = value.get_secret_value()
            values[name] = value
        return values
