services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=opus
      - POSTGRES_USER=opus
      - POSTGRES_PASSWORD=opus
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  opus-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      -  opus_data:/var/opt/opus
    extra_hosts:
      - "opus-docker.localhost:127.0.0.1"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
  opus_data:
