site_name: OPUS
repo_url: https://github.com/ParisAstronomicalDataCentre/OPUS
theme: readthedocs
pages:
- Overview: 'index.md'
- Installation: 'install.md'
- Configuration: 'settings.md'
- User guide: 'user_guide.md'
- Developer guide: 'dev_guide.md'
