site_name: OPUS - Observatoire de Paris UWS Server
repo_url: https://github.com/mservillat/OPUS
pages:
- Overview: 'index.md'
- Installation: 'install.md'
- Configuration: 'settings.md'
- User guide: 'user_guide.md'
- Developer guide: 'dev_guide.md'
