pid       /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/nginx.pid;
error_log /Users/mservillat/Professionnel/GIT/OPUS/var/logs/nginx_error.log;

events {
    worker_connections 1024;
}

http {
    # Access log (using variables)
    access_log /Users/mservillat/Professionnel/GIT/OPUS/var/logs/nginx_access.log combined;

    # Temp dirs (default ones may be owned by root/nobody)
    client_body_temp_path /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/client_body_temp;
    proxy_temp_path       /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/proxy_temp;
    fastcgi_temp_path     /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/fastcgi_temp;
    uwsgi_temp_path       /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/uwsgi_temp;
    scgi_temp_path        /Users/mservillat/Professionnel/GIT/OPUS/var/nginx/scgi_temp;

    # Upstream definitions (uvicorn ports)
    upstream opus_client {
        server 127.0.0.1:8080;
    }
    upstream opus_server {
        server 127.0.0.1:8082;
    }

    server {

        listen 80;
        server_name localhost;

        location = /favicon.ico {
            proxy_pass http://opus_client/favicon.ico ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Opus Client
        location /opus_client/ {
            proxy_pass http://opus_client/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        # Static files
        location /static/ {
            proxy_pass http://opus_client/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Opus Server
        location /opus_server/ {
            proxy_pass http://opus_server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }

        location / {
            return 301 /opus_client/;
        }
    }
}
